import pandas as pd

list_uninsured = ["Abilene, TX Metro Area <br \/> Percent Uninsured:  13.7% <br \/> Number Uninsured:  21,000",
                  "Akron, OH Metro Area <br \/> Percent Uninsured:  5.0% <br \/> Number Uninsured:  35,000",
                  "Albany, GA Metro Area <br \/> Percent Uninsured:  15.2% <br \/> Number Uninsured:  23,000",
                  "Albany, OR Metro Area <br \/> Percent Uninsured:  7.1% <br \/> Number Uninsured:  9,000",
                  "Albany-Schenectady-Troy, NY Metro Area <br \/> Percent Uninsured:  3.1% <br \/> Number Uninsured:  27,000",
                  "Albuquerque, NM Metro Area <br \/> Percent Uninsured:  7.4% <br \/> Number Uninsured:  67,000",
                  "Alexandria, LA Metro Area <br \/> Percent Uninsured:  8.9% <br \/> Number Uninsured:  13,000",
                  "Allentown-Bethlehem-Easton, PA-NJ Metro Area <br \/> Percent Uninsured:  5.5% <br \/> Number Uninsured:  46,000",
                  "Altoona, PA Metro Area <br \/> Percent Uninsured:  4.7% <br \/> Number Uninsured:  6,000",
                  "Amarillo, TX Metro Area <br \/> Percent Uninsured:  15.3% <br \/> Number Uninsured:  39,000",
                  "Ames, IA Metro Area <br \/> Percent Uninsured:  4.9% <br \/> Number Uninsured:  5,000",
                  "Anchorage, AK Metro Area <br \/> Percent Uninsured:  12.2% <br \/> Number Uninsured:  48,000",
                  "Ann Arbor, MI Metro Area <br \/> Percent Uninsured:  2.7% <br \/> Number Uninsured:  10,000",
                  "Anniston-Oxford-Jacksonville, AL Metro Area <br \/> Percent Uninsured:  10.8% <br \/> Number Uninsured:  12,000",
                  "Appleton, WI Metro Area <br \/> Percent Uninsured:  3.6% <br \/> Number Uninsured:  8,000",
                  "Asheville, NC Metro Area <br \/> Percent Uninsured:  11.2% <br \/> Number Uninsured:  51,000",
                  "Athens-Clarke County, GA Metro Area <br \/> Percent Uninsured:  11.3% <br \/> Number Uninsured:  23,000",
                  "Atlanta-Sandy Springs-Roswell, GA Metro Area <br \/> Percent Uninsured:  13.0% <br \/> Number Uninsured:  758,000",
                  "Atlantic City-Hammonton, NJ Metro Area <br \/> Percent Uninsured:  8.7% <br \/> Number Uninsured:  23,000",
                  "Auburn-Opelika, AL Metro Area <br \/> Percent Uninsured:  7.3% <br \/> Number Uninsured:  12,000",
                  "Augusta-Richmond County, GA-SC Metro Area <br \/> Percent Uninsured:  11.0% <br \/> Number Uninsured:  64,000",
                  "Austin-Round Rock, TX Metro Area <br \/> Percent Uninsured:  11.7% <br \/> Number Uninsured:  246,000",
                  "Bakersfield, CA Metro Area <br \/> Percent Uninsured:  7.8% <br \/> Number Uninsured:  67,000",
                  "Baltimore-Columbia-Towson, MD Metro Area <br \/> Percent Uninsured:  4.9% <br \/> Number Uninsured:  136,000",
                  "Bangor, ME Metro Area <br \/> Percent Uninsured:  7.9% <br \/> Number Uninsured:  12,000",
                  "Barnstable Town, MA Metro Area <br \/> Percent Uninsured:  3.1% <br \/> Number Uninsured:  6,000",
                  "Baton Rouge, LA Metro Area <br \/> Percent Uninsured:  7.4% <br \/> Number Uninsured:  61,000",
                  "Battle Creek, MI Metro Area <br \/> Percent Uninsured:  3.8% <br \/> Number Uninsured:  5,000",
                  "Bay City, MI Metro Area <br \/> Percent Uninsured:  5.3% <br \/> Number Uninsured:  5,000",
                  "Beaumont-Port Arthur, TX Metro Area <br \/> Percent Uninsured:  17.4% <br \/> Number Uninsured:  69,000",
                  "Beckley, WV Metro Area <br \/> Percent Uninsured:  6.3% <br \/> Number Uninsured:  7,000",
                  "Bellingham, WA Metro Area <br \/> Percent Uninsured:  4.4% <br \/> Number Uninsured:  10,000",
                  "Bend-Redmond, OR Metro Area <br \/> Percent Uninsured:  7.0% <br \/> Number Uninsured:  13,000",
                  "Billings, MT Metro Area <br \/> Percent Uninsured:  7.0% <br \/> Number Uninsured:  12,000",
                  "Binghamton, NY Metro Area <br \/> Percent Uninsured:  4.3% <br \/> Number Uninsured:  10,000",
                  "Birmingham-Hoover, AL Metro Area <br \/> Percent Uninsured:  8.6% <br \/> Number Uninsured:  97,000",
                  "Bismarck, ND Metro Area <br \/> Percent Uninsured:  7.0% <br \/> Number Uninsured:  9,000",
                  "Blacksburg-Christiansburg-Radford, VA Metro Area <br \/> Percent Uninsured:  7.8% <br \/> Number Uninsured:  14,000",
                  "Bloomington, IL Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  7,000",
                  "Bloomington, IN Metro Area <br \/> Percent Uninsured:  6.6% <br \/> Number Uninsured:  11,000",
                  "Bloomsburg-Berwick, PA Metro Area <br \/> Percent Uninsured:  3.7% <br \/> Number Uninsured:  3,000",
                  "Boise City, ID Metro Area <br \/> Percent Uninsured:  10.5% <br \/> Number Uninsured:  73,000",
                  "Boston-Cambridge-Newton, MA-NH Metro Area <br \/> Percent Uninsured:  3.0% <br \/> Number Uninsured:  144,000",
                  "Boulder, CO Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  13,000",
                  "Bowling Green, KY Metro Area <br \/> Percent Uninsured:  5.5% <br \/> Number Uninsured:  10,000",
                  "Bremerton-Silverdale, WA Metro Area <br \/> Percent Uninsured:  3.8% <br \/> Number Uninsured:  9,000",
                  "Bridgeport-Stamford-Norwalk, CT Metro Area <br \/> Percent Uninsured:  9.2% <br \/> Number Uninsured:  86,000",
                  "Brownsville-Harlingen, TX Metro Area <br \/> Percent Uninsured:  27.6% <br \/> Number Uninsured:  116,000",
                  "Brunswick, GA Metro Area <br \/> Percent Uninsured:  13.8% <br \/> Number Uninsured:  16,000",
                  "Buffalo-Cheektowaga-Niagara Falls, NY Metro Area <br \/> Percent Uninsured:  3.5% <br \/> Number Uninsured:  39,000",
                  "Burlington, NC Metro Area <br \/> Percent Uninsured:  12.4% <br \/> Number Uninsured:  20,000",
                  "Burlington-South Burlington, VT Metro Area <br \/> Percent Uninsured:  3.5% <br \/> Number Uninsured:  7,000",
                  "California-Lexington Park, MD Metro Area <br \/> Percent Uninsured:  4.4% <br \/> Number Uninsured:  5,000",
                  "Canton-Massillon, OH Metro Area <br \/> Percent Uninsured:  6.7% <br \/> Number Uninsured:  26,000",
                  "Cape Coral-Fort Myers, FL Metro Area <br \/> Percent Uninsured:  13.3% <br \/> Number Uninsured:  97,000",
                  "Cape Girardeau, MO-IL Metro Area <br \/> Percent Uninsured:  8.0% <br \/> Number Uninsured:  8,000",
                  "Carbondale-Marion, IL Metro Area <br \/> Percent Uninsured:  6.1% <br \/> Number Uninsured:  8,000",
                  "Carson City, NV Metro Area <br \/> Percent Uninsured:  8.6% <br \/> Number Uninsured:  5,000",
                  "Casper, WY Metro Area <br \/> Percent Uninsured:  14.3% <br \/> Number Uninsured:  11,000",
                  "Cedar Rapids, IA Metro Area <br \/> Percent Uninsured:  3.9% <br \/> Number Uninsured:  10,000",
                  "Chambersburg-Waynesboro, PA Metro Area <br \/> Percent Uninsured:  6.6% <br \/> Number Uninsured:  10,000",
                  "Champaign-Urbana, IL Metro Area <br \/> Percent Uninsured:  3.6% <br \/> Number Uninsured:  9,000",
                  "Charleston, WV Metro Area <br \/> Percent Uninsured:  4.8% <br \/> Number Uninsured:  10,000",
                  "Charleston-North Charleston, SC Metro Area <br \/> Percent Uninsured:  11.3% <br \/> Number Uninsured:  86,000",
                  "Charlotte-Concord-Gastonia, NC-SC Metro Area <br \/> Percent Uninsured:  10.2% <br \/> Number Uninsured:  255,000",
                  "Charlottesville, VA Metro Area <br \/> Percent Uninsured:  7.5% <br \/> Number Uninsured:  17,000",
                  "Chattanooga, TN-GA Metro Area <br \/> Percent Uninsured:  9.7% <br \/> Number Uninsured:  53,000",
                  "Cheyenne, WY Metro Area <br \/> Percent Uninsured:  10.7% <br \/> Number Uninsured:  10,000",
                  "Chicago-Naperville-Elgin, IL-IN-WI Metro Area <br \/> Percent Uninsured:  7.6% <br \/> Number Uninsured:  717,000",
                  "Chico, CA Metro Area <br \/> Percent Uninsured:  5.5% <br \/> Number Uninsured:  12,000",
                  "Cincinnati, OH-KY-IN Metro Area <br \/> Percent Uninsured:  5.0% <br \/> Number Uninsured:  107,000",
                  "Clarksville, TN-KY Metro Area <br \/> Percent Uninsured:  8.3% <br \/> Number Uninsured:  22,000",
                  "Cleveland, TN Metro Area <br \/> Percent Uninsured:  11.2% <br \/> Number Uninsured:  14,000",
                  "Cleveland-Elyria, OH Metro Area <br \/> Percent Uninsured:  5.1% <br \/> Number Uninsured:  103,000",
                  "Coeur d'Alene, ID Metro Area <br \/> Percent Uninsured:  7.5% <br \/> Number Uninsured:  12,000",
                  "College Station-Bryan, TX Metro Area <br \/> Percent Uninsured:  12.6% <br \/> Number Uninsured:  32,000",
                  "Colorado Springs, CO Metro Area <br \/> Percent Uninsured:  7.0% <br \/> Number Uninsured:  48,000",
                  "Columbia, MO Metro Area <br \/> Percent Uninsured:  8.3% <br \/> Number Uninsured:  15,000",
                  "Columbia, SC Metro Area <br \/> Percent Uninsured:  10.0% <br \/> Number Uninsured:  80,000",
                  "Columbus, GA-AL Metro Area <br \/> Percent Uninsured:  11.0% <br \/> Number Uninsured:  32,000",
                  "Columbus, IN Metro Area <br \/> Percent Uninsured:  8.8% <br \/> Number Uninsured:  7,000",
                  "Columbus, OH Metro Area <br \/> Percent Uninsured:  6.6% <br \/> Number Uninsured:  135,000",
                  "Corpus Christi, TX Metro Area <br \/> Percent Uninsured:  17.5% <br \/> Number Uninsured:  78,000",
                  "Corvallis, OR Metro Area <br \/> Percent Uninsured:  4.8% <br \/> Number Uninsured:  4,000",
                  "Crestview-Fort Walton Beach-Destin, FL Metro Area <br \/> Percent Uninsured:  13.2% <br \/> Number Uninsured:  34,000",
                  "Cumberland, MD-WV Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  5,000",
                  "Dallas-Fort Worth-Arlington, TX Metro Area <br \/> Percent Uninsured:  16.5% <br \/> Number Uninsured:  1,210,000",
                  "Dalton, GA Metro Area <br \/> Percent Uninsured:  18.5% <br \/> Number Uninsured:  26,000",
                  "Danville, IL Metro Area <br \/> Percent Uninsured:  6.2% <br \/> Number Uninsured:  5,000",
                  "Daphne-Fairhope-Foley, AL Metro Area <br \/> Percent Uninsured:  9.2% <br \/> Number Uninsured:  19,000",
                  "Davenport-Moline-Rock Island, IA-IL Metro Area <br \/> Percent Uninsured:  4.7% <br \/> Number Uninsured:  18,000",
                  "Dayton, OH Metro Area <br \/> Percent Uninsured:  5.6% <br \/> Number Uninsured:  44,000",
                  "Decatur, AL Metro Area <br \/> Percent Uninsured:  8.5% <br \/> Number Uninsured:  13,000",
                  "Decatur, IL Metro Area <br \/> Percent Uninsured:  3.9% <br \/> Number Uninsured:  4,000",
                  "Deltona-Daytona Beach-Ormond Beach, FL Metro Area <br \/> Percent Uninsured:  11.0% <br \/> Number Uninsured:  71,000",
                  "Denver-Aurora-Lakewood, CO Metro Area <br \/> Percent Uninsured:  7.2% <br \/> Number Uninsured:  207,000",
                  "Des Moines-West Des Moines, IA Metro Area <br \/> Percent Uninsured:  4.4% <br \/> Number Uninsured:  28,000",
                  "Detroit-Warren-Dearborn, MI Metro Area <br \/> Percent Uninsured:  5.0% <br \/> Number Uninsured:  214,000",
                  "Dothan, AL Metro Area <br \/> Percent Uninsured:  9.2% <br \/> Number Uninsured:  13,000",
                  "Dover, DE Metro Area <br \/> Percent Uninsured:  7.6% <br \/> Number Uninsured:  13,000",
                  "Dubuque, IA Metro Area <br \/> Percent Uninsured:  3.4% <br \/> Number Uninsured:  3,000",
                  "Duluth, MN-WI Metro Area <br \/> Percent Uninsured:  4.5% <br \/> Number Uninsured:  12,000",
                  "Durham-Chapel Hill, NC Metro Area <br \/> Percent Uninsured:  10.8% <br \/> Number Uninsured:  61,000",
                  "East Stroudsburg, PA Metro Area <br \/> Percent Uninsured:  6.9% <br \/> Number Uninsured:  12,000",
                  "Eau Claire, WI Metro Area <br \/> Percent Uninsured:  6.0% <br \/> Number Uninsured:  10,000",
                  "El Centro, CA Metro Area <br \/> Percent Uninsured:  6.3% <br \/> Number Uninsured:  11,000",
                  "Elizabethtown-Fort Knox, KY Metro Area <br \/> Percent Uninsured:  4.8% <br \/> Number Uninsured:  7,000",
                  "Elkhart-Goshen, IN Metro Area <br \/> Percent Uninsured:  12.5% <br \/> Number Uninsured:  25,000",
                  "Elmira, NY Metro Area <br \/> Percent Uninsured:  3.9% <br \/> Number Uninsured:  3,000",
                  "El Paso, TX Metro Area <br \/> Percent Uninsured:  20.6% <br \/> Number Uninsured:  169,000",
                  "Enid, OK Metro Area <br \/> Percent Uninsured:  17.8% <br \/> Number Uninsured:  11,000",
                  "Erie, PA Metro Area <br \/> Percent Uninsured:  4.9% <br \/> Number Uninsured:  13,000",
                  "Eugene, OR Metro Area <br \/> Percent Uninsured:  6.5% <br \/> Number Uninsured:  24,000",
                  "Evansville, IN-KY Metro Area <br \/> Percent Uninsured:  6.4% <br \/> Number Uninsured:  20,000",
                  "Fairbanks, AK Metro Area <br \/> Percent Uninsured:  11.2% <br \/> Number Uninsured:  10,000",
                  "Fargo, ND-MN Metro Area <br \/> Percent Uninsured:  5.8% <br \/> Number Uninsured:  14,000",
                  "Farmington, NM Metro Area <br \/> Percent Uninsured:  14.0% <br \/> Number Uninsured:  18,000",
                  "Fayetteville, NC Metro Area <br \/> Percent Uninsured:  10.3% <br \/> Number Uninsured:  36,000",
                  "Fayetteville-Springdale-Rogers, AR-MO Metro Area <br \/> Percent Uninsured:  10.4% <br \/> Number Uninsured:  55,000",
                  "Flagstaff, AZ Metro Area <br \/> Percent Uninsured:  10.2% <br \/> Number Uninsured:  14,000",
                  "Flint, MI Metro Area <br \/> Percent Uninsured:  6.3% <br \/> Number Uninsured:  26,000",
                  "Florence, SC Metro Area <br \/> Percent Uninsured:  9.4% <br \/> Number Uninsured:  19,000",
                  "Florence-Muscle Shoals, AL Metro Area <br \/> Percent Uninsured:  9.1% <br \/> Number Uninsured:  13,000",
                  "Fond du Lac, WI Metro Area <br \/> Percent Uninsured:  3.8% <br \/> Number Uninsured:  4,000",
                  "Fort Collins, CO Metro Area <br \/> Percent Uninsured:  6.3% <br \/> Number Uninsured:  22,000",
                  "Fort Smith, AR-OK Metro Area <br \/> Percent Uninsured:  12.3% <br \/> Number Uninsured:  34,000",
                  "Fort Wayne, IN Metro Area <br \/> Percent Uninsured:  8.0% <br \/> Number Uninsured:  34,000",
                  "Fresno, CA Metro Area <br \/> Percent Uninsured:  7.7% <br \/> Number Uninsured:  75,000",
                  "Gadsden, AL Metro Area <br \/> Percent Uninsured:  11.5% <br \/> Number Uninsured:  12,000",
                  "Gainesville, FL Metro Area <br \/> Percent Uninsured:  9.5% <br \/> Number Uninsured:  27,000",
                  "Gainesville, GA Metro Area <br \/> Percent Uninsured:  17.5% <br \/> Number Uninsured:  35,000",
                  "Gettysburg, PA Metro Area <br \/> Percent Uninsured:  6.2% <br \/> Number Uninsured:  6,000",
                  "Glens Falls, NY Metro Area <br \/> Percent Uninsured:  5.2% <br \/> Number Uninsured:  6,000",
                  "Goldsboro, NC Metro Area <br \/> Percent Uninsured:  13.6% <br \/> Number Uninsured:  16,000",
                  "Grand Forks, ND-MN Metro Area <br \/> Percent Uninsured:  6.1% <br \/> Number Uninsured:  6,000",
                  "Grand Island, NE Metro Area <br \/> Percent Uninsured:  10.5% <br \/> Number Uninsured:  9,000",
                  "Grand Junction, CO Metro Area <br \/> Percent Uninsured:  7.5% <br \/> Number Uninsured:  11,000",
                  "Grand Rapids-Wyoming, MI Metro Area <br \/> Percent Uninsured:  5.0% <br \/> Number Uninsured:  52,000",
                  "Grants Pass, OR Metro Area <br \/> Percent Uninsured:  6.7% <br \/> Number Uninsured:  6,000",
                  "Great Falls, MT Metro Area <br \/> Percent Uninsured:  8.8% <br \/> Number Uninsured:  7,000",
                  "Greeley, CO Metro Area <br \/> Percent Uninsured:  7.7% <br \/> Number Uninsured:  23,000",
                  "Green Bay, WI Metro Area <br \/> Percent Uninsured:  4.9% <br \/> Number Uninsured:  15,000",
                  "Greensboro-High Point, NC Metro Area <br \/> Percent Uninsured:  10.0% <br \/> Number Uninsured:  76,000",
                  "Greenville, NC Metro Area <br \/> Percent Uninsured:  8.0% <br \/> Number Uninsured:  14,000",
                  "Greenville-Anderson-Mauldin, SC Metro Area <br \/> Percent Uninsured:  10.7% <br \/> Number Uninsured:  95,000",
                  "Gulfport-Biloxi-Pascagoula, MS Metro Area <br \/> Percent Uninsured:  13.5% <br \/> Number Uninsured:  52,000",
                  "Hagerstown-Martinsburg, MD-WV Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  15,000",
                  "Hammond, LA Metro Area <br \/> Percent Uninsured:  10.3% <br \/> Number Uninsured:  14,000",
                  "Hanford-Corcoran, CA Metro Area <br \/> Percent Uninsured:  8.4% <br \/> Number Uninsured:  11,000",
                  "Harrisburg-Carlisle, PA Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  32,000",
                  "Harrisonburg, VA Metro Area <br \/> Percent Uninsured:  14.8% <br \/> Number Uninsured:  20,000",
                  "Hartford-West Hartford-East Hartford, CT Metro Area <br \/> Percent Uninsured:  4.1% <br \/> Number Uninsured:  49,000",
                  "Hattiesburg, MS Metro Area <br \/> Percent Uninsured:  13.0% <br \/> Number Uninsured:  19,000",
                  "Hickory-Lenoir-Morganton, NC Metro Area <br \/> Percent Uninsured:  11.7% <br \/> Number Uninsured:  42,000",
                  "Hilton Head Island-Bluffton-Beaufort, SC Metro Area <br \/> Percent Uninsured:  13.8% <br \/> Number Uninsured:  29,000",
                  "Hinesville, GA Metro Area <br \/> Percent Uninsured:  13.4% <br \/> Number Uninsured:  10,000",
                  "Homosassa Springs, FL Metro Area <br \/> Percent Uninsured:  10.0% <br \/> Number Uninsured:  14,000",
                  "Hot Springs, AR Metro Area <br \/> Percent Uninsured:  10.3% <br \/> Number Uninsured:  10,000",
                  "Houma-Thibodaux, LA Metro Area <br \/> Percent Uninsured:  7.4% <br \/> Number Uninsured:  15,000",
                  "Houston-The Woodlands-Sugar Land, TX Metro Area <br \/> Percent Uninsured:  18.2% <br \/> Number Uninsured:  1,243,000",
                  "Huntington-Ashland, WV-KY-OH Metro Area <br \/> Percent Uninsured:  6.9% <br \/> Number Uninsured:  24,000",
                  "Huntsville, AL Metro Area <br \/> Percent Uninsured:  8.8% <br \/> Number Uninsured:  39,000",
                  "Idaho Falls, ID Metro Area <br \/> Percent Uninsured:  6.6% <br \/> Number Uninsured:  10,000",
                  "Indianapolis-Carmel-Anderson, IN Metro Area <br \/> Percent Uninsured:  8.0% <br \/> Number Uninsured:  161,000",
                  "Iowa City, IA Metro Area <br \/> Percent Uninsured:  4.5% <br \/> Number Uninsured:  8,000",
                  "Ithaca, NY Metro Area <br \/> Percent Uninsured:  4.1% <br \/> Number Uninsured:  4,000",
                  "Jackson, MI Metro Area <br \/> Percent Uninsured:  6.1% <br \/> Number Uninsured:  9,000",
                  "Jackson, MS Metro Area <br \/> Percent Uninsured:  10.1% <br \/> Number Uninsured:  57,000",
                  "Jackson, TN Metro Area <br \/> Percent Uninsured:  9.7% <br \/> Number Uninsured:  12,000",
                  "Jacksonville, FL Metro Area <br \/> Percent Uninsured:  10.9% <br \/> Number Uninsured:  162,000",
                  "Jacksonville, NC Metro Area <br \/> Percent Uninsured:  7.4% <br \/> Number Uninsured:  11,000",
                  "Janesville-Beloit, WI Metro Area <br \/> Percent Uninsured:  6.5% <br \/> Number Uninsured:  10,000",
                  "Jefferson City, MO Metro Area <br \/> Percent Uninsured:  10.2% <br \/> Number Uninsured:  14,000",
                  "Johnson City, TN Metro Area <br \/> Percent Uninsured:  10.0% <br \/> Number Uninsured:  20,000",
                  "Johnstown, PA Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  5,000",
                  "Jonesboro, AR Metro Area <br \/> Percent Uninsured:  7.4% <br \/> Number Uninsured:  10,000",
                  "Joplin, MO Metro Area <br \/> Percent Uninsured:  12.6% <br \/> Number Uninsured:  22,000",
                  "Kahului-Wailuku-Lahaina, HI Metro Area <br \/> Percent Uninsured:  4.6% <br \/> Number Uninsured:  8,000",
                  "Kalamazoo-Portage, MI Metro Area <br \/> Percent Uninsured:  5.4% <br \/> Number Uninsured:  18,000",
                  "Kankakee, IL Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  6,000",
                  "Kansas City, MO-KS Metro Area <br \/> Percent Uninsured:  9.1% <br \/> Number Uninsured:  190,000",
                  "Kennewick-Richland, WA Metro Area <br \/> Percent Uninsured:  9.7% <br \/> Number Uninsured:  28,000",
                  "Killeen-Temple, TX Metro Area <br \/> Percent Uninsured:  11.5% <br \/> Number Uninsured:  47,000",
                  "Kingsport-Bristol-Bristol, TN-VA Metro Area <br \/> Percent Uninsured:  7.7% <br \/> Number Uninsured:  23,000",
                  "Kingston, NY Metro Area <br \/> Percent Uninsured:  6.2% <br \/> Number Uninsured:  11,000",
                  "Knoxville, TN Metro Area <br \/> Percent Uninsured:  8.4% <br \/> Number Uninsured:  73,000",
                  "Kokomo, IN Metro Area <br \/> Percent Uninsured:  5.9% <br \/> Number Uninsured:  5,000",
                  "La Crosse-Onalaska, WI-MN Metro Area <br \/> Percent Uninsured:  4.3% <br \/> Number Uninsured:  6,000",
                  "Lafayette, LA Metro Area <br \/> Percent Uninsured:  9.8% <br \/> Number Uninsured:  48,000",
                  "Lafayette-West Lafayette, IN Metro Area <br \/> Percent Uninsured:  7.1% <br \/> Number Uninsured:  15,000",
                  "Lake Charles, LA Metro Area <br \/> Percent Uninsured:  8.3% <br \/> Number Uninsured:  17,000",
                  "Lake Havasu City-Kingman, AZ Metro Area <br \/> Percent Uninsured:  10.4% <br \/> Number Uninsured:  21,000",
                  "Lakeland-Winter Haven, FL Metro Area <br \/> Percent Uninsured:  12.3% <br \/> Number Uninsured:  84,000",
                  "Lancaster, PA Metro Area <br \/> Percent Uninsured:  13.0% <br \/> Number Uninsured:  70,000",
                  "Lansing-East Lansing, MI Metro Area <br \/> Percent Uninsured:  4.5% <br \/> Number Uninsured:  21,000",
                  "Laredo, TX Metro Area <br \/> Percent Uninsured:  28.9% <br \/> Number Uninsured:  79,000",
                  "Las Cruces, NM Metro Area <br \/> Percent Uninsured:  9.5% <br \/> Number Uninsured:  20,000",
                  "Las Vegas-Henderson-Paradise, NV Metro Area <br \/> Percent Uninsured:  11.8% <br \/> Number Uninsured:  257,000",
                  "Lawrence, KS Metro Area <br \/> Percent Uninsured:  7.3% <br \/> Number Uninsured:  9,000",
                  "Lawton, OK Metro Area <br \/> Percent Uninsured:  13.6% <br \/> Number Uninsured:  16,000",
                  "Lebanon, PA Metro Area <br \/> Percent Uninsured:  10.0% <br \/> Number Uninsured:  14,000",
                  "Lewiston, ID-WA Metro Area <br \/> Percent Uninsured:  5.0% <br \/> Number Uninsured:  3,000",
                  "Lewiston-Auburn, ME Metro Area <br \/> Percent Uninsured:  9.1% <br \/> Number Uninsured:  10,000",
                  "Lexington-Fayette, KY Metro Area <br \/> Percent Uninsured:  6.1% <br \/> Number Uninsured:  31,000",
                  "Lima, OH Metro Area <br \/> Percent Uninsured:  7.2% <br \/> Number Uninsured:  7,000",
                  "Lincoln, NE Metro Area <br \/> Percent Uninsured:  6.9% <br \/> Number Uninsured:  23,000",
                  "Little Rock-North Little Rock-Conway, AR Metro Area <br \/> Percent Uninsured:  7.0% <br \/> Number Uninsured:  51,000",
                  "Logan, UT-ID Metro Area <br \/> Percent Uninsured:  7.9% <br \/> Number Uninsured:  11,000",
                  "Longview, TX Metro Area <br \/> Percent Uninsured:  17.2% <br \/> Number Uninsured:  36,000",
                  "Longview, WA Metro Area <br \/> Percent Uninsured:  3.8% <br \/> Number Uninsured:  4,000",
                  "Los Angeles-Long Beach-Anaheim, CA Metro Area <br \/> Percent Uninsured:  8.6% <br \/> Number Uninsured:  1,142,000",
                  "Louisville\/Jefferson County, KY-IN Metro Area <br \/> Percent Uninsured:  5.3% <br \/> Number Uninsured:  68,000",
                  "Lubbock, TX Metro Area <br \/> Percent Uninsured:  12.5% <br \/> Number Uninsured:  39,000",
                  "Lynchburg, VA Metro Area <br \/> Percent Uninsured:  8.2% <br \/> Number Uninsured:  21,000",
                  "Macon-Bibb County, GA Metro Area <br \/> Percent Uninsured:  11.3% <br \/> Number Uninsured:  25,000",
                  "Madera, CA Metro Area <br \/> Percent Uninsured:  8.9% <br \/> Number Uninsured:  13,000",
                  "Madison, WI Metro Area <br \/> Percent Uninsured:  4.2% <br \/> Number Uninsured:  27,000",
                  "Manchester-Nashua, NH Metro Area <br \/> Percent Uninsured:  6.0% <br \/> Number Uninsured:  24,000",
                  "Manhattan, KS Metro Area <br \/> Percent Uninsured:  5.8% <br \/> Number Uninsured:  5,000",
                  "Mankato-North Mankato, MN Metro Area <br \/> Percent Uninsured:  3.5% <br \/> Number Uninsured:  4,000",
                  "Mansfield, OH Metro Area <br \/> Percent Uninsured:  10.2% <br \/> Number Uninsured:  12,000",
                  "McAllen-Edinburg-Mission, TX Metro Area <br \/> Percent Uninsured:  30.0% <br \/> Number Uninsured:  255,000",
                  "Medford, OR Metro Area <br \/> Percent Uninsured:  7.8% <br \/> Number Uninsured:  17,000",
                  "Memphis, TN-MS-AR Metro Area <br \/> Percent Uninsured:  9.8% <br \/> Number Uninsured:  130,000",
                  "Merced, CA Metro Area <br \/> Percent Uninsured:  7.5% <br \/> Number Uninsured:  20,000",
                  "Miami-Fort Lauderdale-West Palm Beach, FL Metro Area <br \/> Percent Uninsured:  15.5% <br \/> Number Uninsured:  950,000",
                  "Michigan City-La Porte, IN Metro Area <br \/> Percent Uninsured:  7.3% <br \/> Number Uninsured:  7,000",
                  "Midland, MI Metro Area <br \/> Percent Uninsured:  3.1% <br \/> Number Uninsured:  3,000",
                  "Midland, TX Metro Area <br \/> Percent Uninsured:  19.4% <br \/> Number Uninsured:  33,000",
                  "Milwaukee-Waukesha-West Allis, WI Metro Area <br \/> Percent Uninsured:  5.5% <br \/> Number Uninsured:  86,000",
                  "Minneapolis-St. Paul-Bloomington, MN-WI Metro Area <br \/> Percent Uninsured:  4.2% <br \/> Number Uninsured:  151,000",
                  "Missoula, MT Metro Area <br \/> Percent Uninsured:  5.4% <br \/> Number Uninsured:  6,000",
                  "Mobile, AL Metro Area <br \/> Percent Uninsured:  10.8% <br \/> Number Uninsured:  44,000",
                  "Modesto, CA Metro Area <br \/> Percent Uninsured:  5.1% <br \/> Number Uninsured:  28,000",
                  "Monroe, LA Metro Area <br \/> Percent Uninsured:  7.6% <br \/> Number Uninsured:  13,000",
                  "Monroe, MI Metro Area <br \/> Percent Uninsured:  4.6% <br \/> Number Uninsured:  7,000",
                  "Montgomery, AL Metro Area <br \/> Percent Uninsured:  8.4% <br \/> Number Uninsured:  30,000",
                  "Morgantown, WV Metro Area <br \/> Percent Uninsured:  5.3% <br \/> Number Uninsured:  7,000",
                  "Morristown, TN Metro Area <br \/> Percent Uninsured:  9.8% <br \/> Number Uninsured:  11,000",
                  "Mount Vernon-Anacortes, WA Metro Area <br \/> Percent Uninsured:  6.6% <br \/> Number Uninsured:  8,000",
                  "Muncie, IN Metro Area <br \/> Percent Uninsured:  7.8% <br \/> Number Uninsured:  9,000",
                  "Muskegon, MI Metro Area <br \/> Percent Uninsured:  3.8% <br \/> Number Uninsured:  6,000",
                  "Myrtle Beach-Conway-North Myrtle Beach, SC-NC Metro Area <br \/> Percent Uninsured:  13.2% <br \/> Number Uninsured:  61,000",
                  "Napa, CA Metro Area <br \/> Percent Uninsured:  7.2% <br \/> Number Uninsured:  10,000",
                  "Naples-Immokalee-Marco Island, FL Metro Area <br \/> Percent Uninsured:  16.0% <br \/> Number Uninsured:  59,000",
                  "Nashville-Davidson--Murfreesboro--Franklin, TN Metro Area <br \/> Percent Uninsured:  9.5% <br \/> Number Uninsured:  179,000",
                  "New Bern, NC Metro Area <br \/> Percent Uninsured:  10.8% <br \/> Number Uninsured:  13,000",
                  "New Haven-Milford, CT Metro Area <br \/> Percent Uninsured:  4.5% <br \/> Number Uninsured:  38,000",
                  "New Orleans-Metairie, LA Metro Area <br \/> Percent Uninsured:  9.0% <br \/> Number Uninsured:  113,000",
                  "New York-Newark-Jersey City, NY-NJ-PA Metro Area <br \/> Percent Uninsured:  7.0% <br \/> Number Uninsured:  1,405,000",
                  "Niles-Benton Harbor, MI Metro Area <br \/> Percent Uninsured:  6.0% <br \/> Number Uninsured:  9,000",
                  "North Port-Sarasota-Bradenton, FL Metro Area <br \/> Percent Uninsured:  11.2% <br \/> Number Uninsured:  89,000",
                  "Norwich-New London, CT Metro Area <br \/> Percent Uninsured:  3.7% <br \/> Number Uninsured:  10,000",
                  "Ocala, FL Metro Area <br \/> Percent Uninsured:  10.5% <br \/> Number Uninsured:  36,000",
                  "Ocean City, NJ Metro Area <br \/> Percent Uninsured:  4.7% <br \/> Number Uninsured:  4,000",
                  "Odessa, TX Metro Area <br \/> Percent Uninsured:  21.1% <br \/> Number Uninsured:  33,000",
                  "Ogden-Clearfield, UT Metro Area <br \/> Percent Uninsured:  6.9% <br \/> Number Uninsured:  46,000",
                  "Oklahoma City, OK Metro Area <br \/> Percent Uninsured:  12.5% <br \/> Number Uninsured:  170,000",
                  "Olympia-Tumwater, WA Metro Area <br \/> Percent Uninsured:  4.9% <br \/> Number Uninsured:  14,000",
                  "Omaha-Council Bluffs, NE-IA Metro Area <br \/> Percent Uninsured:  8.0% <br \/> Number Uninsured:  74,000",
                  "Orlando-Kissimmee-Sanford, FL Metro Area <br \/> Percent Uninsured:  12.5% <br \/> Number Uninsured:  312,000",
                  "Oshkosh-Neenah, WI Metro Area <br \/> Percent Uninsured:  4.7% <br \/> Number Uninsured:  8,000",
                  "Owensboro, KY Metro Area <br \/> Percent Uninsured:  3.5% <br \/> Number Uninsured:  4,000",
                  "Oxnard-Thousand Oaks-Ventura, CA Metro Area <br \/> Percent Uninsured:  8.4% <br \/> Number Uninsured:  72,000",
                  "Palm Bay-Melbourne-Titusville, FL Metro Area <br \/> Percent Uninsured:  9.9% <br \/> Number Uninsured:  58,000",
                  "Panama City, FL Metro Area <br \/> Percent Uninsured:  12.8% <br \/> Number Uninsured:  25,000",
                  "Parkersburg-Vienna, WV Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  5,000",
                  "Pensacola-Ferry Pass-Brent, FL Metro Area <br \/> Percent Uninsured:  10.1% <br \/> Number Uninsured:  47,000",
                  "Peoria, IL Metro Area <br \/> Percent Uninsured:  4.9% <br \/> Number Uninsured:  18,000",
                  "Philadelphia-Camden-Wilmington, PA-NJ-DE-MD Metro Area <br \/> Percent Uninsured:  5.2% <br \/> Number Uninsured:  311,000",
                  "Phoenix-Mesa-Scottsdale, AZ Metro Area <br \/> Percent Uninsured:  10.2% <br \/> Number Uninsured:  479,000",
                  "Pine Bluff, AR Metro Area <br \/> Percent Uninsured:  5.8% <br \/> Number Uninsured:  5,000",
                  "Pittsburgh, PA Metro Area <br \/> Percent Uninsured:  3.5% <br \/> Number Uninsured:  82,000",
                  "Pittsfield, MA Metro Area <br \/> Percent Uninsured:  2.1% <br \/> Number Uninsured:  3,000",
                  "Pocatello, ID Metro Area <br \/> Percent Uninsured:  8.0% <br \/> Number Uninsured:  7,000",
                  "Portland-South Portland, ME Metro Area <br \/> Percent Uninsured:  6.3% <br \/> Number Uninsured:  33,000",
                  "Portland-Vancouver-Hillsboro, OR-WA Metro Area <br \/> Percent Uninsured:  6.2% <br \/> Number Uninsured:  151,000",
                  "Port St. Lucie, FL Metro Area <br \/> Percent Uninsured:  11.6% <br \/> Number Uninsured:  54,000",
                  "Prescott, AZ Metro Area <br \/> Percent Uninsured:  9.5% <br \/> Number Uninsured:  22,000",
                  "Providence-Warwick, RI-MA Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  64,000",
                  "Provo-Orem, UT Metro Area <br \/> Percent Uninsured:  7.5% <br \/> Number Uninsured:  46,000",
                  "Pueblo, CO Metro Area <br \/> Percent Uninsured:  6.5% <br \/> Number Uninsured:  11,000",
                  "Punta Gorda, FL Metro Area <br \/> Percent Uninsured:  11.7% <br \/> Number Uninsured:  21,000",
                  "Racine, WI Metro Area <br \/> Percent Uninsured:  4.4% <br \/> Number Uninsured:  8,000",
                  "Raleigh, NC Metro Area <br \/> Percent Uninsured:  10.0% <br \/> Number Uninsured:  132,000",
                  "Rapid City, SD Metro Area <br \/> Percent Uninsured:  11.7% <br \/> Number Uninsured:  17,000",
                  "Reading, PA Metro Area <br \/> Percent Uninsured:  5.8% <br \/> Number Uninsured:  24,000",
                  "Redding, CA Metro Area <br \/> Percent Uninsured:  6.5% <br \/> Number Uninsured:  12,000",
                  "Reno, NV Metro Area <br \/> Percent Uninsured:  9.9% <br \/> Number Uninsured:  46,000",
                  "Richmond, VA Metro Area <br \/> Percent Uninsured:  8.6% <br \/> Number Uninsured:  109,000",
                  "Riverside-San Bernardino-Ontario, CA Metro Area <br \/> Percent Uninsured:  7.8% <br \/> Number Uninsured:  351,000",
                  "Roanoke, VA Metro Area <br \/> Percent Uninsured:  8.3% <br \/> Number Uninsured:  26,000",
                  "Rochester, MN Metro Area <br \/> Percent Uninsured:  3.9% <br \/> Number Uninsured:  8,000",
                  "Rochester, NY Metro Area <br \/> Percent Uninsured:  3.6% <br \/> Number Uninsured:  39,000",
                  "Rockford, IL Metro Area <br \/> Percent Uninsured:  5.9% <br \/> Number Uninsured:  20,000",
                  "Rocky Mount, NC Metro Area <br \/> Percent Uninsured:  9.8% <br \/> Number Uninsured:  14,000",
                  "Rome, GA Metro Area <br \/> Percent Uninsured:  15.4% <br \/> Number Uninsured:  15,000",
                  "Sacramento--Roseville--Arden-Arcade, CA Metro Area <br \/> Percent Uninsured:  5.0% <br \/> Number Uninsured:  115,000",
                  "Saginaw, MI Metro Area <br \/> Percent Uninsured:  5.2% <br \/> Number Uninsured:  10,000",
                  "St. Cloud, MN Metro Area <br \/> Percent Uninsured:  3.4% <br \/> Number Uninsured:  7,000",
                  "St. George, UT Metro Area <br \/> Percent Uninsured:  13.5% <br \/> Number Uninsured:  22,000",
                  "St. Joseph, MO-KS Metro Area <br \/> Percent Uninsured:  8.7% <br \/> Number Uninsured:  10,000",
                  "St. Louis, MO-IL Metro Area <br \/> Percent Uninsured:  6.3% <br \/> Number Uninsured:  176,000",
                  "Salem, OR Metro Area <br \/> Percent Uninsured:  8.5% <br \/> Number Uninsured:  36,000",
                  "Salinas, CA Metro Area <br \/> Percent Uninsured:  9.9% <br \/> Number Uninsured:  42,000",
                  "Salisbury, MD-DE Metro Area <br \/> Percent Uninsured:  6.2% <br \/> Number Uninsured:  25,000",
                  "Salt Lake City, UT Metro Area <br \/> Percent Uninsured:  9.7% <br \/> Number Uninsured:  116,000",
                  "San Angelo, TX Metro Area <br \/> Percent Uninsured:  15.5% <br \/> Number Uninsured:  18,000",
                  "San Antonio-New Braunfels, TX Metro Area <br \/> Percent Uninsured:  14.5% <br \/> Number Uninsured:  354,000",
                  "San Diego-Carlsbad, CA Metro Area <br \/> Percent Uninsured:  7.7% <br \/> Number Uninsured:  250,000",
                  "San Francisco-Oakland-Hayward, CA Metro Area <br \/> Percent Uninsured:  4.5% <br \/> Number Uninsured:  210,000",
                  "San Jose-Sunnyvale-Santa Clara, CA Metro Area <br \/> Percent Uninsured:  4.2% <br \/> Number Uninsured:  83,000",
                  "San Luis Obispo-Paso Robles-Arroyo Grande, CA Metro Area <br \/> Percent Uninsured:  6.0% <br \/> Number Uninsured:  17,000",
                  "Santa Cruz-Watsonville, CA Metro Area <br \/> Percent Uninsured:  5.5% <br \/> Number Uninsured:  15,000",
                  "Santa Fe, NM Metro Area <br \/> Percent Uninsured:  10.2% <br \/> Number Uninsured:  15,000",
                  "Santa Maria-Santa Barbara, CA Metro Area <br \/> Percent Uninsured:  9.3% <br \/> Number Uninsured:  41,000",
                  "Santa Rosa, CA Metro Area <br \/> Percent Uninsured:  5.3% <br \/> Number Uninsured:  27,000",
                  "Savannah, GA Metro Area <br \/> Percent Uninsured:  14.0% <br \/> Number Uninsured:  53,000",
                  "Scranton--Wilkes-Barre--Hazleton, PA Metro Area <br \/> Percent Uninsured:  4.5% <br \/> Number Uninsured:  24,000",
                  "Seattle-Tacoma-Bellevue, WA Metro Area <br \/> Percent Uninsured:  5.6% <br \/> Number Uninsured:  215,000",
                  "Sebastian-Vero Beach, FL Metro Area <br \/> Percent Uninsured:  10.4% <br \/> Number Uninsured:  16,000",
                  "Sebring, FL Metro Area <br \/> Percent Uninsured:  9.9% <br \/> Number Uninsured:  10,000",
                  "Sheboygan, WI Metro Area <br \/> Percent Uninsured:  5.0% <br \/> Number Uninsured:  6,000",
                  "Sherman-Denison, TX Metro Area <br \/> Percent Uninsured:  15.5% <br \/> Number Uninsured:  20,000",
                  "Shreveport-Bossier City, LA Metro Area <br \/> Percent Uninsured:  7.3% <br \/> Number Uninsured:  31,000",
                  "Sierra Vista-Douglas, AZ Metro Area <br \/> Percent Uninsured:  7.8% <br \/> Number Uninsured:  9,000",
                  "Sioux City, IA-NE-SD Metro Area <br \/> Percent Uninsured:  7.7% <br \/> Number Uninsured:  13,000",
                  "Sioux Falls, SD Metro Area <br \/> Percent Uninsured:  5.8% <br \/> Number Uninsured:  15,000",
                  "South Bend-Mishawaka, IN-MI Metro Area <br \/> Percent Uninsured:  8.0% <br \/> Number Uninsured:  26,000",
                  "Spartanburg, SC Metro Area <br \/> Percent Uninsured:  10.3% <br \/> Number Uninsured:  34,000",
                  "Spokane-Spokane Valley, WA Metro Area <br \/> Percent Uninsured:  5.5% <br \/> Number Uninsured:  30,000",
                  "Springfield, IL Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  8,000",
                  "Springfield, MA Metro Area <br \/> Percent Uninsured:  2.6% <br \/> Number Uninsured:  16,000",
                  "Springfield, MO Metro Area <br \/> Percent Uninsured:  10.2% <br \/> Number Uninsured:  46,000",
                  "Springfield, OH Metro Area <br \/> Percent Uninsured:  6.1% <br \/> Number Uninsured:  8,000",
                  "State College, PA Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  6,000",
                  "Staunton-Waynesboro, VA Metro Area <br \/> Percent Uninsured:  8.8% <br \/> Number Uninsured:  10,000",
                  "Stockton-Lodi, CA Metro Area <br \/> Percent Uninsured:  6.7% <br \/> Number Uninsured:  49,000",
                  "Sumter, SC Metro Area <br \/> Percent Uninsured:  12.7% <br \/> Number Uninsured:  13,000",
                  "Syracuse, NY Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  26,000",
                  "Tallahassee, FL Metro Area <br \/> Percent Uninsured:  8.8% <br \/> Number Uninsured:  33,000",
                  "Tampa-St. Petersburg-Clearwater, FL Metro Area <br \/> Percent Uninsured:  12.1% <br \/> Number Uninsured:  372,000",
                  "Terre Haute, IN Metro Area <br \/> Percent Uninsured:  5.8% <br \/> Number Uninsured:  9,000",
                  "Texarkana, TX-AR Metro Area <br \/> Percent Uninsured:  10.6% <br \/> Number Uninsured:  15,000",
                  "The Villages, FL Metro Area <br \/> Percent Uninsured:  4.6% <br \/> Number Uninsured:  5,000",
                  "Toledo, OH Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  34,000",
                  "Topeka, KS Metro Area <br \/> Percent Uninsured:  7.1% <br \/> Number Uninsured:  16,000",
                  "Trenton, NJ Metro Area <br \/> Percent Uninsured:  8.3% <br \/> Number Uninsured:  31,000",
                  "Tucson, AZ Metro Area <br \/> Percent Uninsured:  8.3% <br \/> Number Uninsured:  83,000",
                  "Tulsa, OK Metro Area <br \/> Percent Uninsured:  13.2% <br \/> Number Uninsured:  130,000",
                  "Tuscaloosa, AL Metro Area <br \/> Percent Uninsured:  6.7% <br \/> Number Uninsured:  16,000",
                  "Tyler, TX Metro Area <br \/> Percent Uninsured:  17.2% <br \/> Number Uninsured:  39,000",
                  "Urban Honolulu, HI Metro Area <br \/> Percent Uninsured:  3.3% <br \/> Number Uninsured:  31,000",
                  "Utica-Rome, NY Metro Area <br \/> Percent Uninsured:  4.8% <br \/> Number Uninsured:  14,000",
                  "Valdosta, GA Metro Area <br \/> Percent Uninsured:  16.3% <br \/> Number Uninsured:  23,000",
                  "Vallejo-Fairfield, CA Metro Area <br \/> Percent Uninsured:  4.9% <br \/> Number Uninsured:  21,000",
                  "Victoria, TX Metro Area <br \/> Percent Uninsured:  17.2% <br \/> Number Uninsured:  17,000",
                  "Vineland-Bridgeton, NJ Metro Area <br \/> Percent Uninsured:  10.3% <br \/> Number Uninsured:  15,000",
                  "Virginia Beach-Norfolk-Newport News, VA-NC Metro Area <br \/> Percent Uninsured:  8.9% <br \/> Number Uninsured:  145,000",
                  "Visalia-Porterville, CA Metro Area <br \/> Percent Uninsured:  7.3% <br \/> Number Uninsured:  34,000",
                  "Waco, TX Metro Area <br \/> Percent Uninsured:  14.6% <br \/> Number Uninsured:  38,000",
                  "Walla Walla, WA Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  4,000",
                  "Warner Robins, GA Metro Area <br \/> Percent Uninsured:  13.7% <br \/> Number Uninsured:  25,000",
                  "Washington-Arlington-Alexandria, DC-VA-MD-WV Metro Area <br \/> Percent Uninsured:  7.6% <br \/> Number Uninsured:  466,000",
                  "Waterloo-Cedar Falls, IA Metro Area <br \/> Percent Uninsured:  4.4% <br \/> Number Uninsured:  7,000",
                  "Watertown-Fort Drum, NY Metro Area <br \/> Percent Uninsured:  4.0% <br \/> Number Uninsured:  4,000",
                  "Wausau, WI Metro Area <br \/> Percent Uninsured:  6.4% <br \/> Number Uninsured:  9,000",
                  "Weirton-Steubenville, WV-OH Metro Area <br \/> Percent Uninsured:  6.0% <br \/> Number Uninsured:  7,000",
                  "Wenatchee, WA Metro Area <br \/> Percent Uninsured:  8.7% <br \/> Number Uninsured:  10,000",
                  "Wheeling, WV-OH Metro Area <br \/> Percent Uninsured:  6.6% <br \/> Number Uninsured:  9,000",
                  "Wichita, KS Metro Area <br \/> Percent Uninsured:  9.5% <br \/> Number Uninsured:  61,000",
                  "Wichita Falls, TX Metro Area <br \/> Percent Uninsured:  15.3% <br \/> Number Uninsured:  21,000",
                  "Williamsport, PA Metro Area <br \/> Percent Uninsured:  6.0% <br \/> Number Uninsured:  7,000",
                  "Wilmington, NC Metro Area <br \/> Percent Uninsured:  10.8% <br \/> Number Uninsured:  31,000",
                  "Winchester, VA-WV Metro Area <br \/> Percent Uninsured:  8.9% <br \/> Number Uninsured:  12,000",
                  "Winston-Salem, NC Metro Area <br \/> Percent Uninsured:  10.5% <br \/> Number Uninsured:  69,000",
                  "Worcester, MA-CT Metro Area <br \/> Percent Uninsured:  2.9% <br \/> Number Uninsured:  27,000",
                  "Yakima, WA Metro Area <br \/> Percent Uninsured:  11.2% <br \/> Number Uninsured:  28,000",
                  "York-Hanover, PA Metro Area <br \/> Percent Uninsured:  5.7% <br \/> Number Uninsured:  25,000",
                  "Youngstown-Warren-Boardman, OH-PA Metro Area <br \/> Percent Uninsured:  5.8% <br \/> Number Uninsured:  31,000",
                  "Yuba City, CA Metro Area <br \/> Percent Uninsured:  6.8% <br \/> Number Uninsured:  12,000",
                  "Yuma, AZ Metro Area <br \/> Percent Uninsured:  11.1% <br \/> Number Uninsured:  22,000"]

cities = []
for i in list_uninsured:
    cities.append(i.split('<')[0].strip())

uninsured = []
for i in list_uninsured:
    uninsured.append(float(i.split('%')[0].strip()[-5:].strip()))

df_uninsured = pd.DataFrame({"cities": cities, "uninsured_percent": uninsured})
df_uninsured.to_csv("data/Job_Security/uninsured_percent.csv")